name: linux

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/macos*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4

      - name: Compile and Test
        run: |
          mix deps.get
          mix deps.compile
          mix compile
          mix test
